kind = "mobile"
previewPath = "/"
title = "Myanmar Lottery Results"
version = "1.0.0"
id = "artifacts/myanmar-lottery"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21152

[services.development]
run = "pnpm --filter @workspace/myanmar-lottery run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/myanmar-lottery", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/myanmar-lottery", "run", "serve" ]

[services.env]
PORT = "21152"
BASE_PATH = "/"
